### ISSUE TITLE
Prototype: Panel Behaviour, spawn despawn, Turn off and on

### ISSUE THREAD

**Issue by feldbacherSimone** [feldbacherSimone/I-used-to-have-a-Voice#14]

**Comment by FrancisvanBacon** [comment]
- [ ] Make Script that automatically assigns and creates appropriate RenderTextures, etc.
- [ ] Fix Bug: Objects still selected when moving out of panel
- [ ] Make Script that deactivates RenderTextures at a certain point
- [ ] Make basic Trigger Scripts, so objects inside are interactable (Drag, Rotate, RubberConstraint, Multi-Click, Hold...)
